# Plugin Demo Options
network="goerli"
sync-mode="fast"
fast-sync-min-peers=1
pruning-enabled=false

data-path="data/goerli"

host-whitelist=["127.0.0.1", "localhost"]

metrics-enabled=true
metrics-host="127.0.0.1"
metrics-port=9545

#This is the custom registered category
metrics-categories=["GAS_SPENDING_METRICS"]
